version: '3.8'
services:
  superset:
    build:
      context: .
      dockerfile: ./deployment/superset/Dockerfile
    container_name: finbreak_superset
    environment:
      - SUPERSET_SECRET_KEY=finbreak
    networks:
      - finbreak-net
    ports:
      - '8088:8088'

networks:
  finbreak-net: